### ISSUE TITLE
Quoting `CLUSTER_SEEDS` list randomly breaks Akka.Cluster formation

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-bootstrap#134]
Affects version 0.5.1 and previous

Cluster formation will be broken, randomly as a result of environment variable randomization, if we quote `CLUSTER_SEEDS`:

```
apiVersion: v1
kind: Namespace
metadata:
  name: lighthouse-sbr2
---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  namespace: lighthouse-sbr2
  labels:
    app: lighthouse
spec:
  clusterIP: None
  ports:
  - port: 4053
  selector:
    app: lighthouse
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: lighthouse-sbr2
  name: lighthouse
  labels:
    app: lighthouse
spec:
  serviceName: lighthouse
  replicas: 2
  selector:
    matchLabels:
      app: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: lighthouse
        image: arkatufus/lighthouse:1.5.2
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: ACTORSYSTEM
          value: AkkaTrader
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).lighthouse"
        - name: CLUSTER_SEEDS
          value: "akka.tcp://$(ACTORSYSTEM)@lighthouse-0.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-1.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-2.lighthouse:4053"
        - name: AKKA__CLUSTER__DOWNING_PROVIDER_CLASS
          value: "Akka.Cluster.SBR.SplitBrainResolverProvider, Akka.Cluster"
        - name: AKKA__CLUSTER__SPLIT_BRAIN_RESOLVER__ACTIVE_STRATEGY
          value: "keep-majority"
        livenessProbe:
          tcpSocket:
            port: 4053
        ports:
        - containerPort: 4053
          protocol: TCP
```

If I unquote `CLUSTER_SEEDS` then cluster formation works fine:

```
apiVersion: v1
kind: Namespace
metadata:
  name: lighthouse-sbr2
---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  namespace: lighthouse-sbr2
  labels:
    app: lighthouse
spec:
  clusterIP: None
  ports:
  - port: 4053
  selector:
    app: lighthouse
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: lighthouse-sbr2
  name: lighthouse
  labels:
    app: lighthouse
spec:
  serviceName: lighthouse
  replicas: 2
  selector:
    matchLabels:
      app: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: lighthouse
        image: arkatufus/lighthouse:1.5.2
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: ACTORSYSTEM
          value: AkkaTrader
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).lighthouse"
        - name: CLUSTER_SEEDS
          value: akka.tcp://$(ACTORSYSTEM)@lighthouse-0.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-1.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-2.lighthouse:4053
        - name: AKKA__CLUSTER__DOWNING_PROVIDER_CLASS
          value: "Akka.Cluster.SBR.SplitBrainResolverProvider, Akka.Cluster"
        - name: AKKA__CLUSTER__SPLIT_BRAIN_RESOLVER__ACTIVE_STRATEGY
          value: "keep-majority"
        livenessProbe:
          tcpSocket:
            port: 4053
        ports:
        - containerPort: 4053
          protocol: TCP
```
